#-------------------------------
# Maven config
#-------------------------------
coffee:
  app:
    projectStage: dev
quarkus:
  log:
    level: INFO
    min-level: ALL
  #    handler:
  #      gelf:
  #        enabled: ${SAMPLER_LOGSTASH_ENABLED:true}
  swagger-ui:
    enable: true
#  jaeger:
#    enabled: ${JAEGER_ENABLED:true}
